/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('@iconify/vue')['Icon']
    Playground: typeof import('./src/views/Playground.vue')['default']
    SoundButton: typeof import('./src/components/SoundButton.vue')['default']
    SourcePanel: typeof import('./src/components/SourcePanel.vue')['default']
  }
}
