# This is a basic workflow to help you get started with Actions

name: Build and check on submit PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [ opened, edited ]
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # install node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      # Runs a single command using the runners shell
      - name: install dependencies
        run: npm install

      # Runs a single command using the runners shell
      - name: try to build the project
        run: npm run build